import catchErrors from "../utils/catch-errors";

export const getUserHandler = catchErrors(async (req, res) => {
    return;
});
